version: '3'

##############################################
##       Docker Services Configuration      ##
##############################################

services:

  ns-ext:
    build: 
      context: ./DNS-ext/Anvers
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      Anvers:
          ipv4_address: 172.18.10.11  
    container_name: ns2


##############################################
##       Docker Networks Configuration      ##
##############################################

networks:

  Anvers:
    ipam:
        driver: default
        config:
            - subnet: 172.18.10.0/24 
              gateway: 172.18.10.242